version: 2
jobs:

  java11:
    docker:
    - image: circleci/openjdk:11-jdk
    working_directory: ~/repo

    environment:
      MAVEN_OPTS: -Xmx1024m -XX:MaxPermSize=256m

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "pom.xml" }}
        - v1-dependencies-

    - run: mvn dependency:go-offline

    - save_cache:
        paths:
        - ~/.m2
        key: v1-dependencies-{{ checksum "pom.xml" }}
    - run: mvn test

workflows:
  version: 2
  build:
    jobs:
    - java11